privilege:
  anonymous:
    - path: /api/user/login/login
      methods: post,get
    - path: /v2/api-docs
      methods: get
    - path: /webjars/**
      methods: get
    - path: /
      methods: get,post
    - path: /error|/login.*|/404|/favicon.ico
      methods: get,post
#    - path: //api/user/menu/**
#      methods: get,post
  authentication:
    - path: /api/user/user/info
      methods: 2222
#    - path: /api/user/menu/**
#      methods: get
  authorization:
    - path: /api/user/user/page
      methods: get
      privileges:
        - admin
        - admin
    - path: /zzzzzz
      methods: 22we22
      privileges:
        - admin
        - admin