#配置端口和项目根路径
server:
  port: 8081
  servlet:
    context-path: /

app:
  name: MyApp
  description: ${app.name} is a Spring Boot application

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/iroma?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

logging:
  path: E:/IdeaProjects/logs/roma


#设置属性
com:
  prop:
    title: skyhang
    description: hello world
    cnName: hello

redis:
  host: 192.168.0.58