spring:
  profiles:
    active: dev
    include: classpath:config/redis
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml

logging:
  config: classpath:config/logback-spring.xml
  name: iroma