#配置端口和项目根路径
server:
  port: 8082
  context-path: /springboot
  
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:330w6/test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

#设置属性
com:
  neo:
    title: skyhang
    description: hello world
    cnName: 123456

#  spring.datasource.url=jdbc:mysql://localhost:3306/test
#  spring.datasource.username=root
#  spring.datasource.password=root
#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#  spring.jpa.properties.hibernate.hbm2ddl.auto=update
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#  spring.jpa.show-sql= true