spring:
  profiles:
    active: dev
    include: privilege
mybatis:
  mapper-locations: classpath:mapper/*/*.xml

logging:
  config: classpath:config/logback-spring.xml
  name: roma
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace


roma:
  security:
    logout: /api/user/login/logout


