spring:
  profiles:
    active: dev
    include: classpath:config/redis
  jackson:
    #date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml

logging:
  config: classpath:config/logback-spring.xml
  name: roma